### ISSUE TITLE
cannot import name 'CaptionBot'

### ISSUE THREAD

**Issue by Delivator** [krikunts/captionbot#1]
`from captionbot import CaptionBot
Traceback (most recent call last):
  File "<pyshell#0>", line 1, in <module>
    from captionbot import CaptionBot
  File "C:\Python34\lib\site-packages\captionbot\__init__.py", line 1, in <module>
    from captionbot import CaptionBot
ImportError: cannot import name 'CaptionBot'`

**Comment by krikunts** [comment]
Oh, I forgot about different import policies in python2 and python3, thank you for pointing it. This issue should be fixed in v0.1.1
