### ISSUE TITLE
ImportError: cannot import name 'urlencode'

### ISSUE THREAD

**Issue by Delivator** [krikunts/captionbot#4]
``` shell
C:\Users\Delivator>python
Python 3.5.2 (v3.5.2:4def2a2901a5, Jun 25 2016, 22:18:55) [MSC v.1900 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> from captionbot import CaptionBot
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\Delivator\AppData\Local\Programs\Python\Python35\lib\site-packages\captionbot\__init__.py", line 1, in <module>
    from .captionbot import CaptionBot
  File "C:\Users\Delivator\AppData\Local\Programs\Python\Python35\lib\site-packages\captionbot\captionbot.py", line 5, in <module>
    from urllib import urlencode
ImportError: cannot import name 'urlencode'
>>>
```

**Comment by krikunts** [comment]
Ah, forgot about urlencode moved to another package in Python 3. This should be fixed in v0.1.3. Thanks for pointing this out.
